package enssp;

import java.io.IOException;
import java.lang.reflect.Modifier;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Emits a JUnit 4 test class. Oracles are regression assertions captured by executing each
 * sequence: returned values of simple types are asserted, expected exceptions are checked with
 * try/fail/catch, and the values of all observers are asserted at the end of each test.
 */
public final class JUnitWriter {

    private final Class<?> cut;
    private final SequenceExecutor exec;
    private final List<Event> observers;

    public JUnitWriter(Class<?> cut, SequenceExecutor exec, List<Event> observers) {
        this.cut = cut;
        this.exec = exec;
        this.observers = observers;
    }

    public Path write(List<List<Event>> suite, Path outDir, String suffix, String header) throws IOException {
        String pkg = cut.getPackage() == null ? "" : cut.getPackage().getName();
        String name = cut.getSimpleName() + suffix;
        StringBuilder b = new StringBuilder();
        if (!pkg.isEmpty()) b.append("package ").append(pkg).append(";\n\n");
        b.append("import static org.junit.Assert.*;\n\nimport org.junit.Test;\n\n");
        b.append("/**\n * Generated by enSSP-J. ").append(header).append("\n */\n");
        b.append("public class ").append(name).append(" {\n");
        int n = 0;
        for (List<Event> seq : suite) {
            SequenceExecutor.Trace t = exec.execute(seq);
            if (!t.valid) continue;
            b.append("\n    @Test(timeout = 4000)\n    public void test").append(String.format("%03d", n++)).append("() throws Throwable {\n");
            String type = cut.getCanonicalName();
            b.append("        ").append(type).append(" cut = ").append(seq.get(0).javaCall(null)).append(";\n");
            for (SequenceExecutor.Step st : t.steps) {
                b.append("        // system ID ").append(st.pre).append(" -> ").append(st.post).append("\n");
                emit(b, st.event.javaCall("cut"), st.event.returnType(), st.value, st.thrown);
            }
            for (Event o : observers) {
                Object v = null; Throwable th = null;
                try { v = o.invoke(t.finalObject); } catch (Throwable x) { th = x; }
                emit(b, o.javaCall("cut"), o.returnType(), v, th);
            }
            b.append("    }\n");
        }
        b.append("}\n");
        Path dir = pkg.isEmpty() ? outDir : outDir.resolve(pkg.replace('.', '/'));
        Files.createDirectories(dir);
        Path file = dir.resolve(name + ".java");
        Files.write(file, b.toString().getBytes(StandardCharsets.UTF_8));
        return file;
    }

    private static void emit(StringBuilder b, String call, Class<?> rt, Object value, Throwable thrown) {
        String ind = "        ";
        if (thrown != null) {
            String ex = accessibleName(thrown.getClass());
            // A flag (rather than fail() inside try) keeps the check correct when X is an AssertionError.
            b.append(ind).append("{\n")
             .append(ind).append("    boolean raised = false;\n")
             .append(ind).append("    try {\n")
             .append(ind).append("        ").append(call).append(";\n")
             .append(ind).append("    } catch (").append(ex).append(" expected) {\n")
             .append(ind).append("        raised = true;\n")
             .append(ind).append("    }\n")
             .append(ind).append("    assertTrue(\"Expected ").append(ex).append("\", raised);\n")
             .append(ind).append("}\n");
            return;
        }
        if (rt == void.class) { b.append(ind).append(call).append(";\n"); return; }
        if (rt == boolean.class) {
            b.append(ind).append((Boolean) value ? "assertTrue(" : "assertFalse(").append(call).append(");\n");
            return;
        }
        if (rt == double.class || rt == float.class) {
            String lit = rt == double.class ? ArgumentPool.doubleLiteral((Double) value) : ArgumentPool.floatLiteral((Float) value);
            b.append(ind).append("assertEquals(").append(lit).append(", ").append(call).append(", 1e-6);\n");
            return;
        }
        if (rt.isPrimitive()) {
            b.append(ind).append("assertEquals(").append(ArgumentPool.rawLiteral(value)).append(", ").append(call).append(");\n");
            return;
        }
        if (value == null) { b.append(ind).append("assertNull(").append(call).append(");\n"); return; }
        if (isSimple(value) && !(value instanceof Double) && !(value instanceof Float)) {
            String lit = value instanceof String ? ArgumentPool.rawLiteral(value)
                : value instanceof Enum ? ArgumentPool.rawLiteral(value)
                : value.getClass().getSimpleName() + ".valueOf(" + ArgumentPool.rawLiteral(value) + ")";
            b.append(ind).append("assertEquals((Object) ").append(lit).append(", (Object) ").append(call).append(");\n");
            return;
        }
        b.append(ind).append("assertNotNull(").append(call).append(");\n");
    }

    private static boolean isSimple(Object v) {
        return v instanceof Integer || v instanceof Long || v instanceof Short || v instanceof Byte
            || v instanceof Boolean || v instanceof Character || v instanceof String
            || (v instanceof Enum && Modifier.isPublic(((Enum<?>) v).getDeclaringClass().getModifiers()));
    }

    /** Nearest public, canonically named class in the exception's hierarchy. */
    static String accessibleName(Class<?> c) {
        for (Class<?> k = c; k != null; k = k.getSuperclass()) {
            if (Modifier.isPublic(k.getModifiers()) && k.getCanonicalName() != null) return k.getCanonicalName();
        }
        return "Throwable";
    }
}
